// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using Siasm;
using System.Collections.Generic;
using System;
using Siasm.Tables;

namespace Siasm
{
   public sealed class ImmutableBuilder : ImmutableBuilderBase
   {
        MemoryDatabase memory;

        public ImmutableBuilder(MemoryDatabase memory)
        {
            this.memory = memory;
        }

        public MemoryDatabase Build()
        {
            return memory;
        }

        public void ReplaceAll(System.Collections.Generic.IList<BattleCardMasterData> data)
        {
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<int>.Default);
            var table = new BattleCardMasterDataTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.BattleFighterMasterDataTable
            
            );
        }

        public void RemoveBattleCardMasterData(int[] keys)
        {
            var data = RemoveCore(memory.BattleCardMasterDataTable.GetRawDataUnsafe(), keys, x => x.Id, System.Collections.Generic.Comparer<int>.Default);
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<int>.Default);
            var table = new BattleCardMasterDataTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.BattleFighterMasterDataTable
            
            );
        }

        public void Diff(BattleCardMasterData[] addOrReplaceData)
        {
            var data = DiffCore(memory.BattleCardMasterDataTable.GetRawDataUnsafe(), addOrReplaceData, x => x.Id, System.Collections.Generic.Comparer<int>.Default);
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<int>.Default);
            var table = new BattleCardMasterDataTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.BattleFighterMasterDataTable
            
            );
        }

        public void ReplaceAll(System.Collections.Generic.IList<BattleFighterMasterData> data)
        {
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<int>.Default);
            var table = new BattleFighterMasterDataTable(newData);
            memory = new MemoryDatabase(
                memory.BattleCardMasterDataTable,
                table
            
            );
        }

        public void RemoveBattleFighterMasterData(int[] keys)
        {
            var data = RemoveCore(memory.BattleFighterMasterDataTable.GetRawDataUnsafe(), keys, x => x.Id, System.Collections.Generic.Comparer<int>.Default);
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<int>.Default);
            var table = new BattleFighterMasterDataTable(newData);
            memory = new MemoryDatabase(
                memory.BattleCardMasterDataTable,
                table
            
            );
        }

        public void Diff(BattleFighterMasterData[] addOrReplaceData)
        {
            var data = DiffCore(memory.BattleFighterMasterDataTable.GetRawDataUnsafe(), addOrReplaceData, x => x.Id, System.Collections.Generic.Comparer<int>.Default);
            var newData = CloneAndSortBy(data, x => x.Id, System.Collections.Generic.Comparer<int>.Default);
            var table = new BattleFighterMasterDataTable(newData);
            memory = new MemoryDatabase(
                memory.BattleCardMasterDataTable,
                table
            
            );
        }

    }
}