// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using Siasm;
using System.Collections.Generic;
using System;
using Siasm.Tables;

namespace Siasm
{
   public sealed class MemoryDatabase : MemoryDatabaseBase
   {
        public BattleCardMasterDataTable BattleCardMasterDataTable { get; private set; }
        public BattleFighterMasterDataTable BattleFighterMasterDataTable { get; private set; }

        public MemoryDatabase(
            BattleCardMasterDataTable BattleCardMasterDataTable,
            BattleFighterMasterDataTable BattleFighterMasterDataTable
        )
        {
            this.BattleCardMasterDataTable = BattleCardMasterDataTable;
            this.BattleFighterMasterDataTable = BattleFighterMasterDataTable;
        }

        public MemoryDatabase(byte[] databaseBinary, bool internString = true, MessagePack.IFormatterResolver formatterResolver = null, int maxDegreeOfParallelism = 1)
            : base(databaseBinary, internString, formatterResolver, maxDegreeOfParallelism)
        {
        }

        protected override void Init(Dictionary<string, (int offset, int count)> header, System.ReadOnlyMemory<byte> databaseBinary, MessagePack.MessagePackSerializerOptions options, int maxDegreeOfParallelism)
        {
            if(maxDegreeOfParallelism == 1)
            {
                InitSequential(header, databaseBinary, options, maxDegreeOfParallelism);
            }
            else
            {
                InitParallel(header, databaseBinary, options, maxDegreeOfParallelism);
            }
        }

        void InitSequential(Dictionary<string, (int offset, int count)> header, System.ReadOnlyMemory<byte> databaseBinary, MessagePack.MessagePackSerializerOptions options, int maxDegreeOfParallelism)
        {
            this.BattleCardMasterDataTable = ExtractTableData<BattleCardMasterData, BattleCardMasterDataTable>(header, databaseBinary, options, xs => new BattleCardMasterDataTable(xs));
            this.BattleFighterMasterDataTable = ExtractTableData<BattleFighterMasterData, BattleFighterMasterDataTable>(header, databaseBinary, options, xs => new BattleFighterMasterDataTable(xs));
        }

        void InitParallel(Dictionary<string, (int offset, int count)> header, System.ReadOnlyMemory<byte> databaseBinary, MessagePack.MessagePackSerializerOptions options, int maxDegreeOfParallelism)
        {
            var extracts = new Action[]
            {
                () => this.BattleCardMasterDataTable = ExtractTableData<BattleCardMasterData, BattleCardMasterDataTable>(header, databaseBinary, options, xs => new BattleCardMasterDataTable(xs)),
                () => this.BattleFighterMasterDataTable = ExtractTableData<BattleFighterMasterData, BattleFighterMasterDataTable>(header, databaseBinary, options, xs => new BattleFighterMasterDataTable(xs)),
            };
            
            System.Threading.Tasks.Parallel.Invoke(new System.Threading.Tasks.ParallelOptions
            {
                MaxDegreeOfParallelism = maxDegreeOfParallelism
            }, extracts);
        }

        public ImmutableBuilder ToImmutableBuilder()
        {
            return new ImmutableBuilder(this);
        }

        public DatabaseBuilder ToDatabaseBuilder()
        {
            var builder = new DatabaseBuilder();
            builder.Append(this.BattleCardMasterDataTable.GetRawDataUnsafe());
            builder.Append(this.BattleFighterMasterDataTable.GetRawDataUnsafe());
            return builder;
        }

        public DatabaseBuilder ToDatabaseBuilder(MessagePack.IFormatterResolver resolver)
        {
            var builder = new DatabaseBuilder(resolver);
            builder.Append(this.BattleCardMasterDataTable.GetRawDataUnsafe());
            builder.Append(this.BattleFighterMasterDataTable.GetRawDataUnsafe());
            return builder;
        }

#if !DISABLE_MASTERMEMORY_VALIDATOR

        public ValidateResult Validate()
        {
            var result = new ValidateResult();
            var database = new ValidationDatabase(new object[]
            {
                BattleCardMasterDataTable,
                BattleFighterMasterDataTable,
            });

            ((ITableUniqueValidate)BattleCardMasterDataTable).ValidateUnique(result);
            ValidateTable(BattleCardMasterDataTable.All, database, "Id", BattleCardMasterDataTable.PrimaryKeySelector, result);
            ((ITableUniqueValidate)BattleFighterMasterDataTable).ValidateUnique(result);
            ValidateTable(BattleFighterMasterDataTable.All, database, "Id", BattleFighterMasterDataTable.PrimaryKeySelector, result);

            return result;
        }

#endif

        static MasterMemory.Meta.MetaDatabase metaTable;

        public static object GetTable(MemoryDatabase db, string tableName)
        {
            switch (tableName)
            {
                case "BattleCardMasterData":
                    return db.BattleCardMasterDataTable;
                case "BattleFighterMasterData":
                    return db.BattleFighterMasterDataTable;
                
                default:
                    return null;
            }
        }

#if !DISABLE_MASTERMEMORY_METADATABASE

        public static MasterMemory.Meta.MetaDatabase GetMetaDatabase()
        {
            if (metaTable != null) return metaTable;

            var dict = new Dictionary<string, MasterMemory.Meta.MetaTable>();
            dict.Add("BattleCardMasterData", Siasm.Tables.BattleCardMasterDataTable.CreateMetaTable());
            dict.Add("BattleFighterMasterData", Siasm.Tables.BattleFighterMasterDataTable.CreateMetaTable());

            metaTable = new MasterMemory.Meta.MetaDatabase(dict);
            return metaTable;
        }

#endif
    }
}