// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Siasm
{
    public sealed class BattleCardAbilityMasterDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Siasm.BattleCardAbilityMasterData>
    {
        // CardAbilityActivateType
        private static global::System.ReadOnlySpan<byte> GetSpan_CardAbilityActivateType() => new byte[1 + 23] { 183, 67, 97, 114, 100, 65, 98, 105, 108, 105, 116, 121, 65, 99, 116, 105, 118, 97, 116, 101, 84, 121, 112, 101 };
        // CardAbilityTargetType
        private static global::System.ReadOnlySpan<byte> GetSpan_CardAbilityTargetType() => new byte[1 + 21] { 181, 67, 97, 114, 100, 65, 98, 105, 108, 105, 116, 121, 84, 97, 114, 103, 101, 116, 84, 121, 112, 101 };
        // CardAbilityType
        private static global::System.ReadOnlySpan<byte> GetSpan_CardAbilityType() => new byte[1 + 15] { 175, 67, 97, 114, 100, 65, 98, 105, 108, 105, 116, 121, 84, 121, 112, 101 };
        // DetailNumber
        private static global::System.ReadOnlySpan<byte> GetSpan_DetailNumber() => new byte[1 + 12] { 172, 68, 101, 116, 97, 105, 108, 78, 117, 109, 98, 101, 114 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Siasm.BattleCardAbilityMasterData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(4);
            writer.WriteRaw(GetSpan_CardAbilityActivateType());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Siasm.CardAbilityActivateType>(formatterResolver).Serialize(ref writer, value.CardAbilityActivateType, options);
            writer.WriteRaw(GetSpan_CardAbilityTargetType());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Siasm.CardAbilityTargetType>(formatterResolver).Serialize(ref writer, value.CardAbilityTargetType, options);
            writer.WriteRaw(GetSpan_CardAbilityType());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Siasm.CardAbilityType>(formatterResolver).Serialize(ref writer, value.CardAbilityType, options);
            writer.WriteRaw(GetSpan_DetailNumber());
            writer.Write(value.DetailNumber);
        }

        public global::Siasm.BattleCardAbilityMasterData Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::Siasm.BattleCardAbilityMasterData();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 23:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_CardAbilityActivateType().Slice(1))) { goto FAIL; }

                        ____result.CardAbilityActivateType = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Siasm.CardAbilityActivateType>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 21:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_CardAbilityTargetType().Slice(1))) { goto FAIL; }

                        ____result.CardAbilityTargetType = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Siasm.CardAbilityTargetType>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 15:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_CardAbilityType().Slice(1))) { goto FAIL; }

                        ____result.CardAbilityType = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Siasm.CardAbilityType>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 12:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_DetailNumber().Slice(1))) { goto FAIL; }

                        ____result.DetailNumber = reader.ReadInt32();
                        continue;

                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
