// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Siasm
{
    public sealed class TechnologyDeveloperMasterDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Siasm.TechnologyDeveloperMasterData>
    {
        // DeveloperName
        private static global::System.ReadOnlySpan<byte> GetSpan_DeveloperName() => new byte[1 + 13] { 173, 68, 101, 118, 101, 108, 111, 112, 101, 114, 78, 97, 109, 101 };
        // ReportFiles
        private static global::System.ReadOnlySpan<byte> GetSpan_ReportFiles() => new byte[1 + 11] { 171, 82, 101, 112, 111, 114, 116, 70, 105, 108, 101, 115 };
        // DevelopmentMemo
        private static global::System.ReadOnlySpan<byte> GetSpan_DevelopmentMemo() => new byte[1 + 15] { 175, 68, 101, 118, 101, 108, 111, 112, 109, 101, 110, 116, 77, 101, 109, 111 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Siasm.TechnologyDeveloperMasterData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(3);
            writer.WriteRaw(GetSpan_DeveloperName());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.DeveloperName, options);
            writer.WriteRaw(GetSpan_ReportFiles());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string[]>(formatterResolver).Serialize(ref writer, value.ReportFiles, options);
            writer.WriteRaw(GetSpan_DevelopmentMemo());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.DevelopmentMemo, options);
        }

        public global::Siasm.TechnologyDeveloperMasterData Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::Siasm.TechnologyDeveloperMasterData();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 13:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_DeveloperName().Slice(1))) { goto FAIL; }

                        ____result.DeveloperName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 11:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_ReportFiles().Slice(1))) { goto FAIL; }

                        ____result.ReportFiles = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string[]>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 15:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_DevelopmentMemo().Slice(1))) { goto FAIL; }

                        ____result.DevelopmentMemo = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        continue;

                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
