// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(24)
            {
                { typeof(global::Siasm.BattleCardAbilityMasterData[]), 0 },
                { typeof(global::Siasm.DeckCardMasterData[]), 1 },
                { typeof(global::Siasm.DeckMasterData[]), 2 },
                { typeof(global::Siasm.DropItemMasterData[]), 3 },
                { typeof(global::Siasm.PassiveAbilityMasterData[]), 4 },
                { typeof(global::Siasm.AttributeResistType), 5 },
                { typeof(global::Siasm.CardAbilityActivateType), 6 },
                { typeof(global::Siasm.CardAbilityTargetType), 7 },
                { typeof(global::Siasm.CardAbilityType), 8 },
                { typeof(global::Siasm.CardReelType), 9 },
                { typeof(global::Siasm.DropInventoryType), 10 },
                { typeof(global::Siasm.EmotionAttributeType), 11 },
                { typeof(global::Siasm.PassiveAbilityType), 12 },
                { typeof(global::Siasm.RiskLevelType), 13 },
                { typeof(global::Siasm.ArchiveMasterData), 14 },
                { typeof(global::Siasm.AttributeResistMasterData), 15 },
                { typeof(global::Siasm.BattleCardAbilityMasterData), 16 },
                { typeof(global::Siasm.BattleCardMasterData), 17 },
                { typeof(global::Siasm.BattleFighterMasterData), 18 },
                { typeof(global::Siasm.DeckCardMasterData), 19 },
                { typeof(global::Siasm.DeckMasterData), 20 },
                { typeof(global::Siasm.DropItemMasterData), 21 },
                { typeof(global::Siasm.PassiveAbilityMasterData), 22 },
                { typeof(global::Siasm.TechnologyDeveloperMasterData), 23 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.ArrayFormatter<global::Siasm.BattleCardAbilityMasterData>();
                case 1: return new global::MessagePack.Formatters.ArrayFormatter<global::Siasm.DeckCardMasterData>();
                case 2: return new global::MessagePack.Formatters.ArrayFormatter<global::Siasm.DeckMasterData>();
                case 3: return new global::MessagePack.Formatters.ArrayFormatter<global::Siasm.DropItemMasterData>();
                case 4: return new global::MessagePack.Formatters.ArrayFormatter<global::Siasm.PassiveAbilityMasterData>();
                case 5: return new MessagePack.Formatters.Siasm.AttributeResistTypeFormatter();
                case 6: return new MessagePack.Formatters.Siasm.CardAbilityActivateTypeFormatter();
                case 7: return new MessagePack.Formatters.Siasm.CardAbilityTargetTypeFormatter();
                case 8: return new MessagePack.Formatters.Siasm.CardAbilityTypeFormatter();
                case 9: return new MessagePack.Formatters.Siasm.CardReelTypeFormatter();
                case 10: return new MessagePack.Formatters.Siasm.DropInventoryTypeFormatter();
                case 11: return new MessagePack.Formatters.Siasm.EmotionAttributeTypeFormatter();
                case 12: return new MessagePack.Formatters.Siasm.PassiveAbilityTypeFormatter();
                case 13: return new MessagePack.Formatters.Siasm.RiskLevelTypeFormatter();
                case 14: return new MessagePack.Formatters.Siasm.ArchiveMasterDataFormatter();
                case 15: return new MessagePack.Formatters.Siasm.AttributeResistMasterDataFormatter();
                case 16: return new MessagePack.Formatters.Siasm.BattleCardAbilityMasterDataFormatter();
                case 17: return new MessagePack.Formatters.Siasm.BattleCardMasterDataFormatter();
                case 18: return new MessagePack.Formatters.Siasm.BattleFighterMasterDataFormatter();
                case 19: return new MessagePack.Formatters.Siasm.DeckCardMasterDataFormatter();
                case 20: return new MessagePack.Formatters.Siasm.DeckMasterDataFormatter();
                case 21: return new MessagePack.Formatters.Siasm.DropItemMasterDataFormatter();
                case 22: return new MessagePack.Formatters.Siasm.PassiveAbilityMasterDataFormatter();
                case 23: return new MessagePack.Formatters.Siasm.TechnologyDeveloperMasterDataFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name
