// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Siasm
{
    public sealed class DeckMasterDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Siasm.DeckMasterData>
    {
        // AchievementLevel
        private static global::System.ReadOnlySpan<byte> GetSpan_AchievementLevel() => new byte[1 + 16] { 176, 65, 99, 104, 105, 101, 118, 101, 109, 101, 110, 116, 76, 101, 118, 101, 108 };
        // DeckCardMasterDataArray
        private static global::System.ReadOnlySpan<byte> GetSpan_DeckCardMasterDataArray() => new byte[1 + 23] { 183, 68, 101, 99, 107, 67, 97, 114, 100, 77, 97, 115, 116, 101, 114, 68, 97, 116, 97, 65, 114, 114, 97, 121 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Siasm.DeckMasterData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(2);
            writer.WriteRaw(GetSpan_AchievementLevel());
            writer.Write(value.AchievementLevel);
            writer.WriteRaw(GetSpan_DeckCardMasterDataArray());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Siasm.DeckCardMasterData[]>(formatterResolver).Serialize(ref writer, value.DeckCardMasterDataArray, options);
        }

        public global::Siasm.DeckMasterData Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::Siasm.DeckMasterData();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 16:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_AchievementLevel().Slice(1))) { goto FAIL; }

                        ____result.AchievementLevel = reader.ReadInt32();
                        continue;
                    case 23:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_DeckCardMasterDataArray().Slice(1))) { goto FAIL; }

                        ____result.DeckCardMasterDataArray = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Siasm.DeckCardMasterData[]>(formatterResolver).Deserialize(ref reader, options);
                        continue;

                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
