// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using Siasm;
using System.Collections.Generic;
using System;

namespace Siasm.Tables
{
   public sealed partial class BattleFighterMasterDataTable : TableBase<BattleFighterMasterData>, ITableUniqueValidate
   {
        public Func<BattleFighterMasterData, int> PrimaryKeySelector => primaryIndexSelector;
        readonly Func<BattleFighterMasterData, int> primaryIndexSelector;


        public BattleFighterMasterDataTable(BattleFighterMasterData[] sortedData)
            : base(sortedData)
        {
            this.primaryIndexSelector = x => x.Id;
            OnAfterConstruct();
        }

        partial void OnAfterConstruct();


        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public BattleFighterMasterData FindById(int key)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].Id;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { return data[mid]; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            return ThrowKeyNotFound(key);
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public bool TryFindById(int key, out BattleFighterMasterData result)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].Id;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { result = data[mid]; return true; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            result = default;
            return false;
        }

        public BattleFighterMasterData FindClosestById(int key, bool selectLower = true)
        {
            return FindUniqueClosestCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<int>.Default, key, selectLower);
        }

        public RangeView<BattleFighterMasterData> FindRangeById(int min, int max, bool ascendant = true)
        {
            return FindUniqueRangeCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<int>.Default, min, max, ascendant);
        }


        void ITableUniqueValidate.ValidateUnique(ValidateResult resultSet)
        {
#if !DISABLE_MASTERMEMORY_VALIDATOR

            ValidateUniqueCore(data, primaryIndexSelector, "Id", resultSet);       

#endif
        }

#if !DISABLE_MASTERMEMORY_METADATABASE

        public static MasterMemory.Meta.MetaTable CreateMetaTable()
        {
            return new MasterMemory.Meta.MetaTable(typeof(BattleFighterMasterData), typeof(BattleFighterMasterDataTable), "BattleFighterMasterData",
                new MasterMemory.Meta.MetaProperty[]
                {
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("Id")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("ProductName")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("ThemeNameMemo")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("TrueName")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("AdmissionName")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("ManagementNumber")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("RiskLevelType")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("DevelopmentMemo")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("AttributeResistMasterData")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("PassiveAbilityMasterDataArray")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("DeckMasterDataArray")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("DropItemMasterDataArray")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("ArchiveMasterData")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleFighterMasterData).GetProperty("TechnologyDeveloperMasterData")),
                },
                new MasterMemory.Meta.MetaIndex[]{
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(BattleFighterMasterData).GetProperty("Id"),
                    }, true, true, System.Collections.Generic.Comparer<int>.Default),
                });
        }

#endif
    }
}