// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using Siasm;
using System.Collections.Generic;
using System;

namespace Siasm.Tables
{
   public sealed partial class BattleCardMasterDataTable : TableBase<BattleCardMasterData>, ITableUniqueValidate
   {
        public Func<BattleCardMasterData, int> PrimaryKeySelector => primaryIndexSelector;
        readonly Func<BattleCardMasterData, int> primaryIndexSelector;


        public BattleCardMasterDataTable(BattleCardMasterData[] sortedData)
            : base(sortedData)
        {
            this.primaryIndexSelector = x => x.Id;
            OnAfterConstruct();
        }

        partial void OnAfterConstruct();


        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public BattleCardMasterData FindById(int key)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].Id;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { return data[mid]; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            return ThrowKeyNotFound(key);
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public bool TryFindById(int key, out BattleCardMasterData result)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].Id;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { result = data[mid]; return true; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            result = default;
            return false;
        }

        public BattleCardMasterData FindClosestById(int key, bool selectLower = true)
        {
            return FindUniqueClosestCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<int>.Default, key, selectLower);
        }

        public RangeView<BattleCardMasterData> FindRangeById(int min, int max, bool ascendant = true)
        {
            return FindUniqueRangeCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<int>.Default, min, max, ascendant);
        }


        void ITableUniqueValidate.ValidateUnique(ValidateResult resultSet)
        {
#if !DISABLE_MASTERMEMORY_VALIDATOR

            ValidateUniqueCore(data, primaryIndexSelector, "Id", resultSet);       

#endif
        }

#if !DISABLE_MASTERMEMORY_METADATABASE

        public static MasterMemory.Meta.MetaTable CreateMetaTable()
        {
            return new MasterMemory.Meta.MetaTable(typeof(BattleCardMasterData), typeof(BattleCardMasterDataTable), "BattleCardMasterData",
                new MasterMemory.Meta.MetaProperty[]
                {
                    new MasterMemory.Meta.MetaProperty(typeof(BattleCardMasterData).GetProperty("Id")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleCardMasterData).GetProperty("CardName")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleCardMasterData).GetProperty("CardReelType")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleCardMasterData).GetProperty("MinReelNumber")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleCardMasterData).GetProperty("MaxReelNumber")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleCardMasterData).GetProperty("FlavorText")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleCardMasterData).GetProperty("EmotionAttributeType")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleCardMasterData).GetProperty("BattleCardAbilityMasterDataArray")),
                    new MasterMemory.Meta.MetaProperty(typeof(BattleCardMasterData).GetProperty("DevelopmentMemo")),
                },
                new MasterMemory.Meta.MetaIndex[]{
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(BattleCardMasterData).GetProperty("Id"),
                    }, true, true, System.Collections.Generic.Comparer<int>.Default),
                });
        }

#endif
    }
}